// Package config defines the schema and (de)serialization of ~/.qilin/config.json.
//
// The config is the user-facing source of truth: `qilin init` writes it,
// `qilin config show|set|edit` mutates it, and `qilin up` / `qilin doctor` read
// it. The Python MCP server doesn't read this file directly; the CLI translates
// it into environment variables (see env.go) that are consumed by Pydantic.
package config

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
)

// SchemaVersion is bumped any time the on-disk format changes in a way that
// requires a migration. The current value is written into every new config
// file so future binaries can detect old layouts and either migrate or warn.
const SchemaVersion = 1

// Defaults mirror the documented Qilin defaults from .env.example. They are
// the wizard's pre-populated values and the fallback for non-interactive init
// when a flag is omitted.
const (
	DefaultOllamaURL       = "http://host.docker.internal:11434"
	DefaultEmbeddingModel  = "nomic-embed-text-v2-moe"
	DefaultEmbeddingDim    = 768
	DefaultCollection      = "memory"
	DefaultMCPHost         = "127.0.0.1"
	DefaultMCPPort         = 8443
	DefaultMCPHTTPPort     = 8080
	DefaultChunkSize       = 450
	DefaultChunkOverlap    = 50
	DefaultEmbedBatchSize  = 16
	DefaultQdrantImageTag  = "v1.18.0"
	DefaultManagedQdrantPort = 6333
)

// QdrantConfig captures everything the CLI needs to know about the vector DB.
// When URL is empty the CLI runs Qdrant as a managed Docker container; when
// it's set the CLI assumes the user is bringing their own.
type QdrantConfig struct {
	URL    string `json:"url,omitempty"`
	APIKey string `json:"api_key,omitempty"`

	// Managed-mode-only fields. Ignored when URL is set.
	Managed     bool   `json:"managed"`
	ImageTag    string `json:"image_tag,omitempty"`
	HostPort    int    `json:"host_port,omitempty"`
}

// OllamaConfig wires up the embedding backend that runs on the host.
type OllamaConfig struct {
	URL            string `json:"url"`
	EmbeddingModel string `json:"embedding_model"`
	EmbeddingDim   int    `json:"embedding_dim"`
}

// ServerConfig describes the MCP/SSE listener exposed to clients.
type ServerConfig struct {
	Host        string `json:"host"`
	Port        int    `json:"port"`
	HTTPEnabled bool   `json:"http_enabled"`
	HTTPPort    int    `json:"http_port"`
}

// TLSConfig points at the cert/key that uvicorn loads. Paths are absolute on
// disk; when the user lets `qilin init` generate a cert we drop them in
// ${QILIN_HOME}/certs/.
type TLSConfig struct {
	CertFile string `json:"cert_file"`
	KeyFile  string `json:"key_file"`

	// SelfSigned is true when the cert was generated by `qilin init` (vs.
	// pointed at a pre-existing PEM). Used by `qilin cert show` to flag
	// "you might want to import this into your OS trust store".
	SelfSigned bool `json:"self_signed"`
}

// ChunkingConfig is rarely touched but exposed so power users can tune it
// without editing .env by hand.
type ChunkingConfig struct {
	SizeTokens    int `json:"size_tokens"`
	OverlapTokens int `json:"overlap_tokens"`
	BatchSize     int `json:"batch_size"`
}

// Config is the root of config.json.
type Config struct {
	SchemaVersion int            `json:"schema_version"`
	Image         string         `json:"image"`
	Collection    string         `json:"default_collection"`
	Qdrant        QdrantConfig   `json:"qdrant"`
	Ollama        OllamaConfig   `json:"ollama"`
	Server        ServerConfig   `json:"server"`
	TLS           TLSConfig      `json:"tls"`
	Chunking      ChunkingConfig `json:"chunking"`
}

// New returns a Config pre-populated with sensible defaults. Callers (mostly
// the init wizard) then override fields based on user input.
func New() Config {
	return Config{
		SchemaVersion: SchemaVersion,
		Image:         "", // filled in by `qilin init` from the build's ImageTag()
		Collection:    DefaultCollection,
		Qdrant: QdrantConfig{
			Managed:  true,
			ImageTag: DefaultQdrantImageTag,
			HostPort: DefaultManagedQdrantPort,
		},
		Ollama: OllamaConfig{
			URL:            DefaultOllamaURL,
			EmbeddingModel: DefaultEmbeddingModel,
			EmbeddingDim:   DefaultEmbeddingDim,
		},
		Server: ServerConfig{
			Host:        DefaultMCPHost,
			Port:        DefaultMCPPort,
			HTTPEnabled: true,
			HTTPPort:    DefaultMCPHTTPPort,
		},
		Chunking: ChunkingConfig{
			SizeTokens:    DefaultChunkSize,
			OverlapTokens: DefaultChunkOverlap,
			BatchSize:     DefaultEmbedBatchSize,
		},
	}
}

// Load reads, decodes, and migrates config.json at path. It returns
// (nil, fs.ErrNotExist-wrapped) when the file is missing so callers can
// detect "user never ran qilin init" without string-matching errors.
func Load(path string) (*Config, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var c Config
	if err := json.Unmarshal(raw, &c); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	migrated, err := migrate(c)
	if err != nil {
		return nil, fmt.Errorf("migrate %s: %w", path, err)
	}
	return &migrated, nil
}

// Save writes the config atomically (temp file + rename) with 0600 perms,
// since the file may carry an API key.
func Save(path string, c *Config) error {
	if c == nil {
		return errors.New("config: Save called with nil config")
	}
	if c.SchemaVersion == 0 {
		c.SchemaVersion = SchemaVersion
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	data, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return fmt.Errorf("encode config: %w", err)
	}
	data = append(data, '\n')
	tmp, err := os.CreateTemp(filepath.Dir(path), ".config.json.*")
	if err != nil {
		return fmt.Errorf("create temp: %w", err)
	}
	tmpName := tmp.Name()
	cleanup := func() { _ = os.Remove(tmpName) }
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		cleanup()
		return fmt.Errorf("write temp: %w", err)
	}
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		cleanup()
		return fmt.Errorf("chmod temp: %w", err)
	}
	if err := tmp.Close(); err != nil {
		cleanup()
		return fmt.Errorf("close temp: %w", err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		cleanup()
		return fmt.Errorf("rename %s -> %s: %w", tmpName, path, err)
	}
	return nil
}

// Validate runs cheap sanity checks against a Config and returns the first
// failure. It is called from `qilin init` (before save) and `qilin up` (before
// shelling out to docker), so users get a clear error instead of a cryptic
// container crash.
func (c *Config) Validate() error {
	if c.Collection == "" {
		return errors.New("default_collection must not be empty")
	}
	if c.Server.Port <= 0 || c.Server.Port > 65535 {
		return fmt.Errorf("server.port out of range: %d", c.Server.Port)
	}
	if c.Server.HTTPEnabled {
		if c.Server.HTTPPort <= 0 || c.Server.HTTPPort > 65535 {
			return fmt.Errorf("server.http_port out of range: %d", c.Server.HTTPPort)
		}
		if c.Server.HTTPPort == c.Server.Port {
			return errors.New("server.http_port must differ from server.port")
		}
	}
	if c.Ollama.URL == "" {
		return errors.New("ollama.url must not be empty")
	}
	if _, err := url.Parse(c.Ollama.URL); err != nil {
		return fmt.Errorf("ollama.url is not a valid URL: %w", err)
	}
	if c.Ollama.EmbeddingDim <= 0 {
		return errors.New("ollama.embedding_dim must be > 0")
	}
	if !c.Qdrant.Managed && c.Qdrant.URL == "" {
		return errors.New("qdrant.url is required when qdrant.managed is false")
	}
	if c.Qdrant.URL != "" {
		if _, err := url.Parse(c.Qdrant.URL); err != nil {
			return fmt.Errorf("qdrant.url is not a valid URL: %w", err)
		}
	}
	if c.TLS.CertFile == "" || c.TLS.KeyFile == "" {
		return errors.New("tls.cert_file and tls.key_file must be set")
	}
	if c.Chunking.SizeTokens < 32 {
		return fmt.Errorf("chunking.size_tokens must be >= 32 (got %d)", c.Chunking.SizeTokens)
	}
	if c.Chunking.OverlapTokens < 0 {
		return errors.New("chunking.overlap_tokens must be >= 0")
	}
	if c.Chunking.BatchSize < 1 {
		return errors.New("chunking.batch_size must be >= 1")
	}
	return nil
}

// migrate brings any older schema up to the current SchemaVersion.
//
// Today there is only one version; this function is a hook so we can add
// upgrades without breaking existing installs.
func migrate(c Config) (Config, error) {
	if c.SchemaVersion > SchemaVersion {
		return c, fmt.Errorf(
			"config schema version %d is newer than this CLI supports (%d); upgrade qilin",
			c.SchemaVersion, SchemaVersion,
		)
	}
	if c.SchemaVersion == 0 {
		// pre-versioned config (or hand-written): assume v1.
		c.SchemaVersion = SchemaVersion
	}
	return c, nil
}
