package config

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// EnvFile renders the .env file consumed by docker compose. It mirrors the
// variables the Python `Settings` class (pydantic-settings) already
// recognizes, so the in-container code needs zero changes to pick the values
// up.
//
// containerCertPath / containerKeyPath are the mount targets inside the
// qilin-mcp container (typically /certs/cert.pem and /certs/key.pem). The
// caller knows them because it also produces the compose mounts.
func (c *Config) EnvFile(containerCertPath, containerKeyPath string) string {
	vars := c.envVars(containerCertPath, containerKeyPath)
	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Auto-generated by `qilin init`. Edit via `qilin config set` instead.\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "%s=%s\n", k, vars[k])
	}
	return b.String()
}

// EnvMap returns the same variables as EnvFile but in map form, suitable for
// passing to exec.Command#Env or `docker compose exec -e KEY=VAL`.
func (c *Config) EnvMap(containerCertPath, containerKeyPath string) map[string]string {
	return c.envVars(containerCertPath, containerKeyPath)
}

func (c *Config) envVars(containerCertPath, containerKeyPath string) map[string]string {
	qdrantURL := c.Qdrant.URL
	if c.Qdrant.Managed {
		// In managed mode the MCP container talks to the qdrant service over
		// the compose network using the service hostname.
		qdrantURL = "http://qdrant:6333"
	}

	httpEnabled := "0"
	if c.Server.HTTPEnabled {
		httpEnabled = "1"
	}

	out := map[string]string{
		"OLLAMA_BASE_URL":      c.Ollama.URL,
		"EMBEDDING_MODEL":      c.Ollama.EmbeddingModel,
		"EMBEDDING_DIM":        strconv.Itoa(c.Ollama.EmbeddingDim),
		"QDRANT_URL":           qdrantURL,
		"QDRANT_API_KEY":       c.Qdrant.APIKey,
		"DEFAULT_COLLECTION":   c.Collection,
		"CHUNK_SIZE_TOKENS":    strconv.Itoa(c.Chunking.SizeTokens),
		"CHUNK_OVERLAP_TOKENS": strconv.Itoa(c.Chunking.OverlapTokens),
		"EMBED_BATCH_SIZE":     strconv.Itoa(c.Chunking.BatchSize),
		"MCP_HOST":             "0.0.0.0", // inside the container; the host bind is set in compose
		"MCP_PORT":             strconv.Itoa(c.Server.Port),
		"MCP_HTTP_PORT":        strconv.Itoa(c.Server.HTTPPort),
		"MCP_HTTP_ENABLED":     httpEnabled,
		"TLS_CERT_FILE":        containerCertPath,
		"TLS_KEY_FILE":         containerKeyPath,
	}
	return out
}
